# Prototype for masking k contiguous sentences

In [31]:
import numpy as np
rng = np.random.default_rng()
import os
os.chdir("..")
os.getcwd()

'/home/flavio/repositories/projects/odissei-life2vec/life-sequencing-dutch'

In [32]:
from pop2vec.llm.src.tasks.sentence_masking import mask_tokens_in_sentences

In [2]:

def merge_intervals(intervals):
    """Merge intervals to be non-overlapping.
    Source: https://github.com/facebookresearch/SpanBERT/blob/main/pretraining/fairseq/data/masking.py
    """
    intervals = sorted(intervals, key=lambda x : x[0])
    merged = []
    for interval in intervals:
        # if the list of merged intervals is empty or if the current
        # interval does not overlap with the previous, simply append it.
        if not merged or merged[-1][1] + 1 < interval[0]:
            merged.append(interval)
        else:
        # otherwise, there is overlap, so we merge the current and previous
        # intervals.
            merged[-1][1] = max(merged[-1][1], interval[1])

    return merged

def create_covered_indices(spans, max_index=None):
    """From a list of spans, create all indices covered by them."""
    spans = np.array(spans)
    if not max_index:
        max_index = spans[:, 1].max()

    covered = np.zeros(max_index, dtype=bool)
    for start, end in spans:
        covered[start:end] = True

    return np.where(covered)[0]

    



In [13]:
def span_masking(sentence_lengths, mask_frac=0.3, k=3):
    n_sentences = len(sentence_lengths)
    n_tokens = sum(sentence_lengths)
    cumsum_lengths = np.cumsum(sentence_lengths)
    spans = []

    span_starts = rng.choice(np.arange(n_sentences), size=n_sentences, replace=False)
    # span_lengths = rng.geometric(p=0.4, size = 10) # we'll probably need a higher p than 0.2 since we're masking at the sentence level
    span_lengths = np.full(n_sentences, k)
    print(f"{span_lengths=}")

    n_masked_tokens = 0
    for span_start, span_length in zip(span_starts, span_lengths):
        span_end = span_start + span_length
        span_end = min(span_end, n_sentences-1)
        tokens_in_span = cumsum_lengths[span_end] - cumsum_lengths[span_start]
        if (n_masked_tokens + tokens_in_span) / n_tokens > mask_frac:
            # print("Reached mask_frac")
            break
        spans.append([span_start, span_end])
        spans = merge_intervals(spans)
        print(f"spans are: {spans}")
        n_masked_tokens += tokens_in_span
        print(f"while loop is at {n_masked_tokens / n_tokens} ")

    return create_covered_indices(spans)



In [23]:
sentence_lengths = rng.choice(np.arange(5), size=20)
sentences_to_mask = span_masking(sentence_lengths, mask_frac=0.6, k=2)
# the function should be called after `find_sentences_to_mask` (which will need to return also the sentence lengths)


span_lengths=array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
spans are: [[2, 4]]
while loop is at 0.1891891891891892 
spans are: [[0, 4]]
while loop is at 0.35135135135135137 
spans are: [[0, 4], [13, 15]]
while loop is at 0.35135135135135137 
spans are: [[0, 4], [9, 11], [13, 15]]
while loop is at 0.40540540540540543 
spans are: [[0, 4], [9, 11], [13, 15], [18, 19]]
while loop is at 0.4864864864864865 
spans are: [[0, 4], [9, 11], [13, 19]]
while loop is at 0.5945945945945946 
Reached mask_frac


In [24]:
sentences_to_mask
# this can be plugged in to the `mask_tokens_in_sentence` function

array([ 0,  1,  2,  3,  9, 10, 13, 14, 15, 16, 17, 18])

In [25]:
sentence_lengths

array([2, 4, 2, 3, 4, 4, 0, 0, 3, 0, 0, 2, 0, 3, 0, 0, 3, 1, 3, 3])

In [33]:
?mask_tokens_in_sentences

Signature:
mask_tokens_in_sentences(
    token_sequence: 'NDArray[np.int_]',
    sentence_starts_and_ends: 'NDArray[np.int_]',
    sentences_to_mask: 'NDArray[np.int_]',
    mask_id: 'int',
    len_target_array: 'int',
    fill_val_target_idx: 'int',
) -> 'tuple[NDArray[np.int_], NDArray[np.int_], NDArray[np.int_]]'
Docstring:
Mask all tokens belonging to the same sentences.

Args:
    token_sequence (np.ndarray): sequence of tokens to be masked.
    sentence_starts_and_ends (np.ndarray): the indices of non-sentence tokens surrounding sentences.
        These are SEP tokens, and any general token before the first sentence. Masking a whole
        sentence will mask all tokens *between* two surrounding, non-sentence tokens.
    sentences_to_mask (np.ndarray): indices of sentences, among all sentences, to be masked.
    mask_id (int): the token ID for the mask.
    len_target_array (int): length of the array returned for the indices and true
        values of the masked tokens. Keeping t

In [ ]:
mask_tokens_in_sentences(
    
)


In [34]:
sentence_lengths

array([2, 4, 2, 3, 4, 4, 0, 0, 3, 0, 0, 2, 0, 3, 0, 0, 3, 1, 3, 3])

In [45]:
# create input sequence
sep_token = 0
sequence = [sep_token]
max_token_id = 100
for sent_length in sentence_lengths:
    print(f"{sequence=}")
    tokens = rng.choice(np.arange(1, max_token_id), sent_length)
    sentence = tokens + [sep_token]
    print(f"{sentence=}")
    sequence = sequence + sentence
    

sequence=[0]
sentence=array([97, 67])
sequence=array([97, 67])
sentence=array([ 7, 62, 17, 40])


ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [39]:
myarr = rng.choice(np.arange(1, max_token_id), 5)
[1] + myarr

array([30, 16, 72, 75, 11])